In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.3.2'

In [6]:
df = pd.read_csv("car_fuel_efficiency.csv")

In [9]:
df.shape

(9704, 11)

In [14]:
df.fuel_type.nunique()

2

In [15]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [21]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

In [22]:
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.describe()

count    3247.000000
mean       14.973830
std         2.578345
min         6.886245
25%        13.252010
50%        15.034670
75%        16.726318
max        23.759123
Name: fuel_efficiency_mpg, dtype: float64

In [42]:
median_pre = df.horsepower.median()
median_pre

149.0

In [52]:
max_count_hp = df.groupby('horsepower').horsepower.count().max()
df2 = df['horsepower'].fillna(max_count_hp)
median_post = df2.median()
median_post

146.0

In [25]:
df_asia = df[df['origin'] == 'Asia']
df_asia = df_asia[['vehicle_weight', 'model_year']]
x = df_asia.head(7).values
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [33]:
xtx = x.T.dot(x)
xtx

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [34]:
xtx_inv = np.linalg.inv(xtx)
xtx_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [31]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [37]:
w = xtx_inv.dot(x.T).dot(y)
w

array([0.01386421, 0.5049067 ])

In [38]:
w.sum()

np.float64(0.5187709081074025)